
services:
  db:
    image: postgres
    container_name: postgres_deployment
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mempaste
    networks:
      - test_network
  mempaste-api:
    networks:
      - test_network
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=mempaste_api=trace,info
      - DATABASE_URL=postgres://postgres:postgres@postgres_deployment:5432/mempaste
    volumes:
      - /var/log/mempaste:/app/logs
    # Overrides default command so things don't shut down after the process ends.
    ports:
      - 4444:4444


networks:
  test_network:
    driver: bridge